### ISSUE TITLE
Je <hr> tag kan voor problemen zorgen

### ISSUE THREAD

**Issue by smolgeorgie** [annelinderaadsheer/the-startup-responsive-interactieve-website#4]
Een <hr tag kan problemen veroorzaken met toegankelijkheid, bijvoorbeeld met het lezen d.m.v. een screenreader. 

Hier een artikel met meer informatie over de <hr tag: [<hr tag artikel](https://mgearon.com/html/horizontal-rules/)

Mijn suggestie is om een area-hidden true aan vast te koppelen, zodat deze niet wordt opgelezen tijdens het gebruik van bijvoorbeeld een screenreader. Zo kan je ook laten zien dat je bezig bent met toegankelijkheid ;)

**Comment by annelinderaadsheer** [comment]
Dankjewel voor de tip! Opgelost :)

**Comment by KrijnHoetmer** [comment]
Dit is niet helemaal de oplossing, maar laten we het over `aria-label` later nog eens hebben..
